### ISSUE TITLE
ToolBarStyle.background,

### ISSUE THREAD

**Issue by MischaKr** [the-airbender/quill_html_editor#62] opened 2023-04-07 12:12 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Flutter Doctor**
Please run `flutter doctor` in the terminal and add the  log here.

**Additional context**

**Comment by the-airbender** [comment] 2023-04-08 07:24
Hi @MischaKr,

I am assuming this is a duplicate of the issue you created #63
Closing this issue. 

Thanks :)

**Closed by the-airbender** 2023-04-08 07:24 UTC

**Comment by MischaKr** [comment] 2023-04-08 11:24
Yes this was a mistake, thanks for closing it.
